Repository TigerPathApp/tigerpath, pull requests merged in 2018-09, with the labels that each got.

#123 Add colors to tutorial text
  tigerpath/static/app/js/tutorial.js
Labels: enhancement

#135 Add CEE major
  tigerpath/fixtures/major_mappings.json
  tigerpath/majors_and_certificates/majors/CEE_2018.json
  tigerpath/majors_and_certificates/scripts/verifier.py
Labels: new major

#146 Search text changed on search by req
  frontend/src/Requirements.js
  frontend/src/Search.js
Labels: UI, enhancement

#139 Add MAE major
  tigerpath/fixtures/major_mappings.json
  tigerpath/majors_and_certificates/majors/MAE_2018.json
  tigerpath/majors_and_certificates/scripts/verifier_tests/10.test.expected
  tigerpath/majors_and_certificates/scripts/verifier_tests/15.test
  tigerpath/majors_and_certificates/scripts/verifier_tests/15.test.expected
  tigerpath/majors_and_certificates/scripts/verifier_tests/9.test.expected
Labels: new major

#121 Add popovers for requirements
  frontend/src/Requirements.css
  frontend/src/Requirements.js
  frontend/src/Search.js
  tigerpath/majors_and_certificates/scripts/verifier.py
Labels: UI, new feature

#152 Add a nicer message for unsupported majors
  frontend/src/Search.js
Labels: UI, enhancement

#151 Add course settling alert icon
  frontend/src/Requirements.css
  frontend/src/Requirements.js
Labels: UI, enhancement

#140 Update the list of supported majors on the about page
  tigerpath/templates/tigerpath/about.html
Labels: docs
