Repository TigerPathApp/tigerpath, pull requests merged in 2020-08, with the labels that each got.

#368 Implement class year differences
  tigerpath/majors_and_certificates/README.md
  tigerpath/majors_and_certificates/scripts/verifier.py
Labels: highly requested, new feature, verifier

#370 Use student class years instead of hardcoded 2018
  config/settings/base.py
  tigerpath/majors_and_certificates/scripts/verifier.py
  tigerpath/views.py
Labels: verifier

#372 Implement example class year differences for COS
  tigerpath/majors_and_certificates/majors/COS-AB_2018.json
  tigerpath/majors_and_certificates/majors/COS-BSE_2018.json
Labels: requirement files

#377 [Fix] Enforce no_req not contributing to requirement counts
  tigerpath/majors_and_certificates/scripts/verifier.py
Labels: verifier

#383 Allow ISC 231-234 to satisfy COS 126 pre-req for COS AB and BSE majors
  tigerpath/majors_and_certificates/majors/COS-AB.json
  tigerpath/majors_and_certificates/majors/COS-BSE.json
Labels: bug

#378 Update distribution requirements for the class of 2024
  tigerpath/majors_and_certificates/degrees/AB.json
  tigerpath/majors_and_certificates/degrees/BSE.json
Labels: requirement files

#375 Fix misspelling of POL Prerequisites for Political Economy track
  tigerpath/majors_and_certificates/majors/POL.json
Labels: requirement files
